fixtures:
  repositories:
    accounts: "https://github.com/puppetlabs/puppetlabs-accounts.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    collectd: "https://github.com/voxpupuli/puppet-collectd.git"
    datacat: "https://github.com/richardc/puppet-datacat.git"
    elasticsearch: "https://github.com/elastic/puppet-elasticsearch.git"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    extlib: "https://github.com/voxpupuli/puppet-extlib.git"
    file_concat: "https://github.com/electrical/puppet-lib-file_concat.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    flink: "https://github.com/attachmentgenie/attachmentgenie-flink.git"
    foreman: "https://github.com/theforeman/puppet-foreman.git"
    foreman_proxy: "https://github.com/theforeman/puppet-foreman_proxy.git"
    gcc: "https://github.com/puppetlabs/puppetlabs-gcc.git"
    gitlab: "https://github.com/vshn/puppet-gitlab.git"
    grafana: "https://github.com/bfraser/puppet-grafana.git"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"
    icinga2: "https://github.com/Icinga/puppet-icinga2-rewrite.git"
    icingaweb2: "https://github.com/Icinga/puppet-icingaweb2.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    influxdb: "https://github.com/n1tr0g/golja-influxdb.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
    jenkins: "https://github.com/jenkinsci/puppet-jenkins.git"
    kibana4: "https://github.com/lesaux/puppet-kibana4.git"
    kafka: "https://github.com/voxpupuli/puppet-kafka.git"
    logstash: "https://github.com/elastic/puppet-logstash.git"
    mailhog: "https://github.com/attachmentgenie/attachmentgenie-mailhog.git"
    memcached: "https://github.com/saz/puppet-memcached.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    neo4j: "https://github.com/mlambrichs/puppet-neo4j.git"
    nginx: "https://github.com/voxpupuli/puppet-nginx.git"
    ntp:  "https://github.com/puppetlabs/puppetlabs-ntp.git"
    postgresql: "https://github.com/puppetlabs/puppetlabs-postgresql.git"
    prometheus: "https://github.com/brutus333/puppet-prometheus.git"
    puppet: "https://github.com/theforeman/puppet-puppet.git"
    puppetdb: "https://github.com/puppetlabs/puppetlabs-puppetdb.git"
    rundeck: "https://github.com/voxpupuli/puppet-rundeck.git"
    selinux: "https://github.com/jfryman/puppet-selinux.git"
    staging: "https://github.com/voxpupuli/puppet-staging.git"
    sudo: "https://github.com/saz/puppet-sudo.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    sysctl: "https://github.com/thias/puppet-sysctl.git"
    systemd: "https://github.com/camptocamp/puppet-systemd.git"
    timezone: "https://github.com/attachmentgenie/attachmentgenie-timezone.git"
    zookeeper: "https://github.com/deric/puppet-zookeeper.git"
  symlinks:
    "profiles": "#{source_dir}"
