fixtures:
  repositories:
    accounts: "https://github.com/camptocamp/puppet-accounts.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "profiles": "#{source_dir}"
