fixtures:
  repositories:
    accounts: "https://github.com/puppetlabs/puppetlabs-accounts.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    collectd: "https://github.com/voxpupuli/puppet-collectd.git"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    file_concat: "https://github.com/electrical/puppet-lib-file_concat.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    gcc: "https://github.com/puppetlabs/puppetlabs-gcc.git"
    gitlab: "https://github.com/vshn/puppet-gitlab.git"
    grafana: "https://github.com/bfraser/puppet-grafana.git"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"
    influxdb: "https://github.com/n1tr0g/golja-influxdb.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
    jenkins: "https://github.com/jenkinsci/puppet-jenkins.git"
    kafka: "https://github.com/voxpupuli/puppet-kafka.git"
    logstash: "https://github.com/elastic/puppet-logstash.git"
    neo4j: "https://github.com/mlambrichs/puppet-neo4j.git"
    nginx: "https://github.com/voxpupuli/puppet-nginx.git"
    ntp:  "https://github.com/puppetlabs/puppetlabs-ntp.git"
    prometheus: "https://github.com/brutus333/puppet-prometheus.git"
    puppet: "https://github.com/theforeman/puppet-puppet.git"
    python: "https://github.com/stankevich/puppet-python.git"
    selinux: "https://github.com/jfryman/puppet-selinux.git"
    stacks: "https://github.com/attachmentgenie/attachmentgenie-stacks.git"
    staging: "https://github.com/voxpupuli/puppet-staging.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "https://github.com/camptocamp/puppet-systemd.git"
    timezone: "https://github.com/attachmentgenie/attachmentgenie-timezone.git"
    zookeeper: "https://github.com/deric/puppet-zookeeper.git"
  symlinks:
    "profiles": "#{source_dir}"
