fixtures:
  repositories:
    accounts: "git@github.com:camptocamp/puppet-accounts.git"
    concat: "git@github.com:puppetlabs/puppetlabs-concat.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "profiles": "#{source_dir}"
